### ISSUE TITLE
I'm having trouble running the application

### ISSUE THREAD

**Issue by rafaelneiva** [hernandazevedo/moviedb#12]
Hello Hernand,
My name is Rafael, I'm an Android developer at Zup. I'm trying to run your app, but I'm having some issues. I liked your code but I was not able to test the app. Even the apk file you provided in the e-mail to Rodolpho didn't work. I tried this apk https://www.dropbox.com/s/valzr3uxjch6id1/presentation-release.apk?dl=1

Could you double check the apk? Or provide another?

And about the issues when I tried to run the app by the code, my guess is something happening with native-lib. I'm attaching here some prints with the errors.

<img width="553" alt="screen shot 2018-11-13 at 11 13 33 am" src="https://user-images.githubusercontent.com/4072756/48415710-40213080-e735-11e8-9373-8e2fb6f9e91a.png">
<img width="396" alt="screen shot 2018-11-13 at 11 13 21 am" src="https://user-images.githubusercontent.com/4072756/48415711-40b9c700-e735-11e8-9e62-195ad81d86a2.png">

**Comment by hernandazevedo** [comment]
I think its about the architecture I´ve used to compile the c++ library.

I have tested on my phone(Xiao Mi A1) and it worked, maybe because it has the arch that the library(.so) was compiled for.

The project was only compiling for armeabi-v7, I have changed the code on v1.0.2 to:
abiFilters 'x86','armeabi-v7a'

Please check the last release v1.0.2, download the signed apk and try to install on your phone.
Here the link: 
https://app.bitrise.io/artifact/9648012/p/4a193a0a117a8946d6fc7442c55f6d08

And please tell me if it worked. Thanks in advance.
